// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: is_chirpy_red.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const isChirpyRed = `-- name: IsChirpyRed :exec
UPDATE users SET is_chirpy_red = TRUE
WHERE id = $1
`

func (q *Queries) IsChirpyRed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, isChirpyRed, id)
	return err
}
